### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [dustin638/plexrequest#42]
Greetings, I'm a graphic designer and I like contributing to open source projects. I'm offering my services to create a logo for yours, it's totally free and we will be working together to create the perfect logo that fits your project best.

If you accept, let me know if you have any preferences (colors, style, etc) or not.

Best regards.

**Comment by dustin638** [comment]
Very kind of you! Let me give it some though and I'll get back to you.

**Comment by dustin638** [comment]
@michaelizer I've come up with a few ideas I'd like to bounce off you. Where would you like to continue this conversation?

**Comment by michaelizer** [comment]
Perfect, I'll start working on it 👍

**Comment by dustin638** [comment]
Awesome, much appreciated! Will of course give you a plug in the readme once you're done.

Would love to be able to drop the logo on the navbar in place of "Plex Request" so if you could design it in a way it wouldn't clash with any colors, that'd be excellent. 
https://gyazo.com/78dd3b1cb467ee95da6e774147976466

**Comment by michaelizer** [comment]
What do you think?

![plex_requestrecurso_35](https://user-images.githubusercontent.com/35619342/41207323-fd5756d0-6ce1-11e8-96bb-23c88cfd0ced.png)

**Comment by michaelizer** [comment]
Here you go ([#56](https://github.com/dustin638/plexrequest/pull/56)). It was a real pleasure, enjoy it!

**Comment by dustin638** [comment]
Merged. Also added you to the readme. Thanks again!
